import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header, Contact } from "@/components"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="px-2 sm:px-8 md:px-24 lg:px-48 xl:px-72">
          <Header />
          {children}
        </div>
      </body>
    </html >
  );
}
